In [1]:
!pip install datawrapper

Collecting datawrapper
  Downloading datawrapper-2.0.14-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from datawrapper) (8.7.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from datawrapper) (13.9.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from datawrapper) (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datawrapper) (2.2.2)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from datawrapper) (2.11.10)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from datawrapper) (7.34.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->datawrapper) (3.23.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (75.2.0)
Collecting jedi>=0.16 (from ipython->datawrapper)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->datawrapper) (4.9.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->datawrapper) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datawrapper) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datawrapper) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datawrapper) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->datawrapper) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->datawrapper) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->datawrapper) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->datawrapper) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->datawrapper) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->datawrapper) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->datawrapper) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->datawrapper) (2025.10.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->datawrapper) (4.0.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->datawrapper) (0.8.5)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->datawrapper) (0.1.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->datawrapper) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->datawrapper) (0.2.14)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datawrapper) (1.17.0)
Downloading datawrapper-2.0.14-py3-none-any.whl (102 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.4/102.4 kB 3.0 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.7 MB/s eta 0:00:00
Installing collected packages: jedi, datawrapper
Successfully installed datawrapper-2.0.14 jedi-0.19.2

In [41]:
%env DATAWRAPPER_ACCESS_TOKEN=

env: DATAWRAPPER_ACCESS_TOKEN=

In [4]:
import datawrapper as dw

In [5]:
dw.Datawrapper().get_my_account()

{'id': 1017377,
 'email': '',
 'name': 'isabellaalvarezlalama',
 'role': 'editor',
 'language': 'en-US',
 'presenceColor': 'color-dw-presence-50',
 'avatar': 'https://avatars.githubusercontent.com/u/229181004?v=4',
 'customAvatar': 'https://avatars.githubusercontent.com/u/229181004?v=4',
 'teams': [],
 'workspaces': [{'slug': 'hmmheizztp',
   'name': 'isabellaalvarezlalama',
   'avatar': 'https://avatars.githubusercontent.com/u/229181004?v=4',
   'color': 'color-dw-presence-50',
   'personalAppearance': True}],
 'chartCount': 2,
 'url': '/v3/users/1017377',
 'activeTeam': None}

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/palewire/first-automated-chart/main/_notebooks/arrests.csv",
    parse_dates=["ArrestDateTime"]
)

In [8]:
df.head()

,RowID,X,Y,IncidentNumber,ArrestNumber,Age,Gender,Race,ArrestDateTime,ArrestLocation,...,ChargeDescription,District,Post,Neighborhood,Latitude,Longitude,GeoLocation,Shape,Year,year
0,29,1.401347e+06,608148.870493,22L09338,23000037.0,39.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
1,30,1.401347e+06,608148.870493,22L09338,23000039.0,50.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
2,31,NaN,NaN,NaN,23000010.0,27.0,M,B,2022-12-31 23:40:00,NaN,...,FAILURE TO APPEAR,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
3,32,1.417636e+06,595206.835862,22L09343,23000050.0,42.0,M,B,2022-12-31 23:15:00,500 DOLPHIN ST,...,HAND GUN VIOLATION,Central,123.0,Upton,39.3004,-76.6279,"(39.3004,-76.6279)",NaN,2022,2022
4,33,NaN,NaN,22L09312,22157183.0,43.0,F,W,2022-12-31 21:00:00,1500 BECKLOW AVE,...,STOLEN AUTO,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022

In [9]:
df['year'] = df.ArrestDateTime.dt.year

In [10]:
df.year.value_counts()

year
2010    45224
2011    43364
2012    42333
2013    39542
2014    37078
2015    25732
2016    23089
2017    21989
2018    20543
2019    19407
2023    13566
2020    13162
2022    12360
2021    11130
Name: count, dtype: int64

In [11]:
totals_by_year = df.year.value_counts().sort_index().reset_index()

In [12]:
chart = dw.ColumnChart(
    title="Baltimore Arrests",
    data=totals_by_year
)

In [13]:
chart.create()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='', source_url='', byline='', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [14]:
chart.publish()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='', source_url='', byline='', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [15]:
chart.display()

In [16]:
chart.source_name = "OpenBaltimore"
chart.source_url = "https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about"
chart.byline = "First Automated Chart"
chart.update()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='First Automated Chart', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [17]:
chart.publish()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='First Automated Chart', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [18]:
chart.display()

In [23]:
chart.source_name = "OpenBaltimore"
chart.source_url = "https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about"
chart.byline = "Isabella Alvarez"
chart.update()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Isabella Alvarez', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color='#E6E6FA', negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [24]:
chart.publish()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Isabella Alvarez', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color='#E6E6FA', negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [25]:
chart.display()

In [26]:
chart.base_color = "#004FA2"

In [27]:
chart.update()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Isabella Alvarez', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color='#004FA2', negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [42]:
chart.publish()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Isabella Alvarez', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='jbhyE', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color='#004FA2', negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [29]:
chart.display()

In [30]:
df.head()

,RowID,X,Y,IncidentNumber,ArrestNumber,Age,Gender,Race,ArrestDateTime,ArrestLocation,...,ChargeDescription,District,Post,Neighborhood,Latitude,Longitude,GeoLocation,Shape,Year,year
0,29,1.401347e+06,608148.870493,22L09338,23000037.0,39.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
1,30,1.401347e+06,608148.870493,22L09338,23000039.0,50.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
2,31,NaN,NaN,NaN,23000010.0,27.0,M,B,2022-12-31 23:40:00,NaN,...,FAILURE TO APPEAR,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
3,32,1.417636e+06,595206.835862,22L09343,23000050.0,42.0,M,B,2022-12-31 23:15:00,500 DOLPHIN ST,...,HAND GUN VIOLATION,Central,123.0,Upton,39.3004,-76.6279,"(39.3004,-76.6279)",NaN,2022,2022
4,33,NaN,NaN,22L09312,22157183.0,43.0,F,W,2022-12-31 21:00:00,1500 BECKLOW AVE,...,STOLEN AUTO,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022

In [31]:
df.District.value_counts()

District
Western      29842
Central      28501
Eastern      28114
Southern     25780
Northeast    24180
Southeast    23710
Northwest    22044
Southwest    21822
Northern     13087
Name: count, dtype: int64

In [35]:
def create_chart(district: str) -> str:
    """Create a Datawrapper column chart of arrests by year in a Baltimore police district.

    Args:
        district: The name of the district to chart.

    Returns:
        The chart's embed code.
    """
    # Filter the dataframe to the provided district
    district_df = df[df.District == district]

    # Count the number of arrests in each year
    district_by_year = district_df.year.value_counts().sort_index().reset_index()

    # Create the chart with Datawrapper
    chart = dw.ColumnChart(
        # Use the district name in the title
        title=f"Arrests in Baltimore's {district} District",
        # Pass in the filtered data
        data=district_by_year,
        base_color="#004FA2",
        source_name="OpenBaltimore",
        source_url="https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about",
        byline="First Automated Chart",
    )

    # Create the chart
    chart.create()

    # Publish the chart
    chart.publish()

    # Return the chart's embed code
    return chart.display()

In [36]:
create_chart("Western")

In [37]:
create_chart("Eastern")

In [38]:
# Create an empty list to hold the charts
chart_list = []

# Loop through the unique districts...
for district in df.District.dropna().unique():
    # Print a message to the console
    print(f"Creating chart for the {district} District")

    # Create a chart for the district and save it as a variable
    c = create_chart(district)

    # Add the chart to the list
    chart_list.append(c)

Creating chart for the Northwest District
Creating chart for the Central District
Creating chart for the Western District
Creating chart for the Eastern District
Creating chart for the Northeast District
Creating chart for the Southern District
Creating chart for the Southeast District
Creating chart for the Northern District
Creating chart for the Southwest District

In [39]:
from IPython.display import display

In [40]:
display(*chart_list)